Add Layer0
redwoodjs/deploy-target-ci pull request #54
Opened 2022-03-16 19:05 UTC by tristanlee85

2022-03-19 01:44 UTC, thedavidprice commented on layer0/api/db/schema.prisma
> +  binaryTargets = ["native","rhel-openssl-1.0.x"]
I'm going to try with just native unless you know definitively that won't work.

2022-03-19 01:44 UTC, thedavidprice commented on layer0/api/db/schema.prisma
> +  binaryTargets = ["native","rhel-openssl-1.0.x"]
I'm going to try with just native unless you know definitively that won't work.

2022-03-19 01:45 UTC, thedavidprice commented on layer0/routes.js
> +export default new Router().use(redwoodRoutes)
Curious about what this does. Are there Docs or a quick explanation?

2022-03-19 01:45 UTC, thedavidprice commented on layer0/routes.js
> +export default new Router().use(redwoodRoutes)
Curious about what this does. Are there Docs or a quick explanation?

2022-03-19 01:54 UTC, thedavidprice commented on layer0/routes.js
> +export default new Router().use(redwoodRoutes)
Ah, found this: https://docs.layer0.co/guides/redwoodjs

2022-03-19 01:54 UTC, thedavidprice commented on layer0/routes.js
> +export default new Router().use(redwoodRoutes)
Ah, found this: https://docs.layer0.co/guides/redwoodjs

2022-03-19 02:26 UTC, thedavidprice requested changes
@tristanlee85 I sent you a direct message with video for further discussion. I'm understanding much better what's supposed to be going on, but I'm running into performance issues (navigating pages is crashing site) and Auth is broken.

Look for my message in Slack with full details.

If we need, we can merge this PR to see how the CI is working and continue from there. I did make a change to schema.prisma --> none of our other deployments for AWS Lambdas require anything but `binaryTargets = "native"`, although that wasn't always the case. Just let me know if I'm missing some information.

2022-03-19 02:35 UTC, thedavidprice commented on .github/workflows/build-test.yaml
> +  layer0:
CI for the project; required for deployment action to run

2022-03-19 02:39 UTC, thedavidprice commented on .github/workflows/deploy-layer0.yml
> +          node-version: '16'
This shouldn't have anything to do with built functions (unless I misunderstand how layer0 build is working). Redwood will build the API functions for Node.js v12, which we'll bump to v14 in a few months.

Just let me know if there's a reason this won't work.

2022-03-19 02:40 UTC, thedavidprice commented on layer0/api/db/schema.prisma
> +  binaryTargets = ["native"]
I'm going to try with just native unless you know definitively that won't work.

2022-03-21 19:01 UTC, tristanlee85 commented on .github/workflows/deploy-layer0.yml
> +          node-version: '16'
When Layer0 does its build of the router handler function, it's possible there could be issues with having that handler (not the RW functions) built with Node 16, but then run under Node 14 in AWS. We can try it with Node 16 though and see if we identify any issues.

2022-03-21 19:02 UTC, tristanlee85 commented on layer0/api/db/schema.prisma
> +  binaryTargets = ["native"]
I recall getting this error again during this project too. I'm not sure if it is related to GH action doing a native build that then differs from the env in AWS. The build will be successful, but requests that use the API may fail. Again, we can try this just as native to get the workflow to run and adjust later if needed.

2022-03-21 21:07 UTC, thedavidprice submitted a review, later dismissed

2022-03-21 21:22 UTC, merged